### ISSUE TITLE
molecule ignores molecule-vagrant 

### ISSUE THREAD

**Issue by oschlueter** [ansible-community/molecule-vagrant#131]
Hello!

I cannot use `vagrant` as driver for my Ansible role testing. I was able to reproduce my problem with a clean slate. Here's the setup:
 
    $ python --version  # using Python 3.6 due to company restrictions
    Python 3.6.14
    $ python -m venv venv
    $ source venv/bin/activate
    $ pip install --upgrade pip
    [...]
    $ pip --version
    pip 21.2.4 from [...]
    $ cat requirements.txt. # using Ansible 2.8 due to company restrictions
    ansible==2.8.20
    molecule==3.3.4
    molecule-vagrant==0.6.3
    $ pip install -r requirements.txt
    [...]

Here's how I create the role:

    $ mol init role nginx -d vagrant
    INFO     Initializing new role nginx...
    No config file found; using defaults
    - nginx was created successfully
    INFO     Initialized role in /Users/oschlueter/git/ansible/roles/nginx successfully.
    $ grep -ri docker nginx  # no mention of docker in role directory
    $

Here's how I reproduce the error:

    $ cd nginx
    $ cat molecule/default/molecule.yml 
    ---
    dependency:
      name: galaxy
    driver:
      name: vagrant
    platforms:
      - name: instance
    provisioner:
      name: ansible
    verifier:
      name: ansible
    $ mol check
    Traceback (most recent call last):
      File "/Users/oschlueter/git/ansible/roles/venv/bin/mol", line 8, in <module>
        sys.exit(main())
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
        return self.main(*args, **kwargs)
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/click/core.py", line 1062, in main
        rv = self.invoke(ctx)
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/click/core.py", line 1668, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/click/core.py", line 763, in invoke
        return __callback(*args, **kwargs)
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/click/decorators.py", line 26, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule/command/check.py", line 111, in check
        base.execute_cmdline_scenarios(scenario_name, args, command_args)
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule/command/base.py", line 98, in execute_cmdline_scenarios
        get_configs(args, command_args, ansible_args, glob_str), scenario_name
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule/command/base.py", line 192, in get_configs
        for c in glob.glob(glob_str)
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule/command/base.py", line 192, in <listcomp>
        for c in glob.glob(glob_str)
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule/config.py", line 60, in __call__
        obj.after_init()
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule/config.py", line 107, in after_init
        self.config = self._reget_config()
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule/config.py", line 272, in _reget_config
        env = util.merge_dicts(os.environ, self.env)
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule/config.py", line 190, in env
        "MOLECULE_INSTANCE_CONFIG": self.driver.instance_config,
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule/config.py", line 174, in driver
        driver = api.drivers(config=self)[driver_name]
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule/api.py", line 29, in __getitem__
        return self.__dict__[i]
    KeyError: 'docker'

I can install molecule-docker to satisfy the requirement but then molecule fails when apparently using the `docker` driver:

    $ pip install molecule[docker]
    [...]
    Successfully installed docker-5.0.2 molecule-docker-0.2.4 websocket-client-1.2.1
    $ mol check
    INFO     default scenario test matrix: dependency, cleanup, destroy, create, prepare, converge, check, cleanup, destroy
    INFO     Performing prerun...
    WARNING  Failed to guess project directory using git:
    INFO     Guessed /Users/oschlueter/git/ansible/roles/nginx as project root directory
    WARNING  Computed fully qualified role name of nginx does not follow current galaxy requirements.
    Please edit meta/main.yml and assure we can correctly determine full role name:
    
    galaxy_info:
    role_name: my_name  # if absent directory name hosting role is used instead
    namespace: my_galaxy_namespace  # if absent, author is used instead
    
    Namespace: https://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations
    Role: https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names
    
    As an alternative, you can add 'role-name' to either skip_list or warn_list.
    
    INFO     Using /Users/oschlueter/.cache/ansible-lint/b425c8/roles/nginx symlink to current repository in order to enable Ansible to find the role using its expected full name.
    INFO     Added ANSIBLE_ROLES_PATH=~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/Users/oschlueter/.cache/ansible-lint/b425c8/roles
    INFO     Running default > dependency
    WARNING  Skipping, missing the requirements file.
    WARNING  Skipping, missing the requirements file.
    INFO     Running default > cleanup
    WARNING  Skipping, cleanup playbook not configured.
    INFO     Running default > destroy
    INFO     Sanity checks: 'docker'
    
    PLAY [Destroy] ********************************************************************************************************************************************************************
    
    TASK [Destroy molecule instance(s)] ***********************************************************************************************************************************************
    changed: [localhost] => (item=instance)
    
    TASK [Wait for instance(s) deletion to complete] **********************************************************************************************************************************
    FAILED - RETRYING: Wait for instance(s) deletion to complete (300 retries left).
    ok: [localhost] => (item={'started': 1, 'finished': 0, 'ansible_job_id': '279133361101.13767', 'results_file': '/Users/oschlueter/.ansible_async/279133361101.13767', 'changed': True, 'failed': False, 'item': {'name': 'instance'}, 'ansible_loop_var': 'item'})
    
    TASK [Delete docker network(s)] ***************************************************************************************************************************************************
    
    PLAY RECAP ************************************************************************************************************************************************************************
    localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
    
    INFO     Running default > create
    
    PLAY [Create] *********************************************************************************************************************************************************************
    
    TASK [Log into a Docker registry] *************************************************************************************************************************************************
    skipping: [localhost] => (item={'name': 'instance'})
    
    TASK [Check presence of custom Dockerfiles] ***************************************************************************************************************************************
    ok: [localhost] => (item={'name': 'instance'})
    
    TASK [Create Dockerfiles from image names] ****************************************************************************************************************************************
    fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'image'\n\nThe error appears to be in '/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule_docker/playbooks/create.yml': line 34, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Create Dockerfiles from image names\n      ^ here\n"}
    
    PLAY RECAP ************************************************************************************************************************************************************************
    localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0
    
    CRITICAL Ansible return code was 2, command was: ansible-playbook --inventory /Users/oschlueter/.cache/molecule/nginx/default/inventory --skip-tags molecule-notest,notest /Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule_docker/playbooks/create.yml

**Comment by oschlueter** [comment]
I'm facing the same problem with molecule 3.4.0. Same steps as above but with 

    $ cat requirements.txt 
    ansible==2.8.20
    molecule==3.4.0
    molecule-vagrant==0.6.3

**Comment by apatard** [comment]
Sounds weird that there's no error from molecule. Maybe a bug in molecule. Don't know. Did you check with ``molecule --version`` that molecule-vagrant is detected ? 
python 3.6 is still tested in molecule-vagrant CI and it's working afaics. Did you check that all dependencies for molecule-vagrant are there (python-vagrant, jinja >= 2.11) ? If a dep is missing, install it and check if it's fine. In this case, molecule should probably issue a warning that the driver failed to work. If everything is already there, you'll have to run molecule with debug mode in hope something interesting will be in the logs.

**Comment by oschlueter** [comment]
It seems that the plugin was installed successfully:

    $ molecule --version
    molecule 3.3.4 using python 3.6
        ansible:2.8.20
        delegated:3.3.4 from molecule
        vagrant:0.6.3 from molecule_vagrant

The debug output looks the same to me:

    $ mol --debug check
    Traceback (most recent call last):
      File "/Users/oschlueter/git/ansible/roles/venv/bin/mol", line 8, in <module>
        sys.exit(main())
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
        return self.main(*args, **kwargs)
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/click/core.py", line 1062, in main
        rv = self.invoke(ctx)
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/click/core.py", line 1668, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/click/core.py", line 763, in invoke
        return __callback(*args, **kwargs)
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/click/decorators.py", line 26, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule/command/check.py", line 111, in check
        base.execute_cmdline_scenarios(scenario_name, args, command_args)
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule/command/base.py", line 98, in execute_cmdline_scenarios
        get_configs(args, command_args, ansible_args, glob_str), scenario_name
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule/command/base.py", line 192, in get_configs
        for c in glob.glob(glob_str)
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule/command/base.py", line 192, in <listcomp>
        for c in glob.glob(glob_str)
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule/config.py", line 60, in __call__
        obj.after_init()
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule/config.py", line 107, in after_init
        self.config = self._reget_config()
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule/config.py", line 272, in _reget_config
        env = util.merge_dicts(os.environ, self.env)
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule/config.py", line 190, in env
        "MOLECULE_INSTANCE_CONFIG": self.driver.instance_config,
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule/config.py", line 174, in driver
        driver = api.drivers(config=self)[driver_name]
      File "/Users/oschlueter/git/ansible/roles/venv/lib/python3.6/site-packages/molecule/api.py", line 29, in __getitem__
        return self.__dict__[i]
    KeyError: 'docker'

**Comment by oschlueter** [comment]
Probably a bug in molecule as I was able to reproduce this problem with `molecule-ec2` as well. I opened a bug report with [molecule itself](https://github.com/ansible-community/molecule/issues/3231) and will close this report.
