### ISSUE TITLE
Cannot login into a Libvirt VM using `molecule login`

### ISSUE THREAD

**Issue by FedericoAntoniazzi** [ansible-community/molecule-vagrant#165]
## How to reproduce
1. Create a scenario and copy my configuration
2. Use `molecule create`
3. Use `molecule converge`
4. After that, try to login (`molecule login`)

An error occurs:
```
❯ molecule list
INFO     Running default > list
                ╷             ╷                  ╷               ╷         ╷            
  Instance Name │ Driver Name │ Provisioner Name │ Scenario Name │ Created │ Converged  
╶───────────────┼─────────────┼──────────────────┼───────────────┼─────────┼───────────╴
  instance      │ vagrant     │ ansible          │ default       │ true    │ true       
                ╵             ╵                  ╵               ╵         ╵            
❯ molecule login
INFO     Running default > login
Traceback (most recent call last):
  File "/usr/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/molecule/command/login.py", line 166, in login
    base.execute_subcommand(scenario.config, subcommand)
  File "/usr/lib/python3.10/site-packages/molecule/command/base.py", line 149, in execute_subcommand
    return command(config).execute()
  File "/usr/lib/python3.10/site-packages/molecule/logger.py", line 188, in wrapper
    rt = func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/molecule/command/login.py", line 101, in execute
    self._get_login(hostname)
  File "/usr/lib/python3.10/site-packages/molecule/command/login.py", line 146, in _get_login
    app.runtime.exec(cmd)
  File "/usr/lib/python3.10/site-packages/ansible_compat/runtime.py", line 138, in exec
    result = run_func(
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/env ssh 192.168.121.140 -l vagrant -p 22 -i /home/federico/.cache/molecule/grafana/default/.vagrant/machines/instance/libvirt/private_key -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no'
```

But if I try to run that command manually:
```
❯ /usr/bin/env ssh 192.168.121.140 -l vagrant -p 22 -i /home/federico/.cache/molecule/grafana/default/.vagrant/machines/instance/libvirt/private_key -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no
Last login: Tue Feb  8 16:02:13 2022 from 192.168.121.1
vagrant@instance:~$ 
```

## Scenario configuration file
```yaml
---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: instance
    box: generic/ubuntu2004
    memory: 2048
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: ansible

```

## Notes
- OS: `Arch Linux`
- Vagrant version: `2.2.19`
- molecule-vagrant version: `v1.0.0`
- Driver: `libvirt`

**Comment by apatard** [comment]
hm.. it really smells like https://github.com/ansible-community/molecule/issues/3435

**Comment by iinuwa** [comment]
@apatard, yes I think it is a regression in molecule 3.6.0. I believe I've narrowed down the issue in issue you linked.

This can probably be closed.
