### ISSUE TITLE
AttributeError: 'AnsibleModule' object has no attribute 'result'

### ISSUE THREAD

**Issue by bendem** [ansible-community/molecule-vagrant#38]
When running a scenario with multiple boxes using VBox, if one of the box fails while the other succeed, the succeeded boxes are not marked as created so running `molecule create` again causes errors.

First pass, half of the instances fail:

<details>
<summary>click for logs</summary>

```
(ansible) ➜  nexus git:(main) ✗ molecule -c molecule/default/wsl.yml --debug converge
--> Test matrix

└── default
    ├── dependency
    ├── create
    ├── prepare
    └── converge

--> Inventory /home/bendem/projects/architecture.vdl/ansible-10-486.git/ansible/playbooks/nexus/molecule/default/../../../../inventory/group_vars/ linked to /home/bendem/.cache/molecule/nexus/default/inventory/group_vars
--> Scenario: 'default'
--> Action: 'dependency'
Skipping, missing the requirements file.
Skipping, missing the requirements file.
--> Inventory /home/bendem/projects/architecture.vdl/ansible-10-486.git/ansible/playbooks/nexus/molecule/default/../../../../inventory/group_vars/ linked to /home/bendem/.cache/molecule/nexus/default/inventory/group_vars
--> Scenario: 'default'
--> Action: 'create'
DEBUG: ANSIBLE ENVIRONMENT
---
ANSIBLE_COLLECTIONS_PATHS: /home/bendem/.cache/molecule/nexus/default/collections:/home/bendem/.ansible:/usr/share/ansible/collections:/etc/ansible/collections
ANSIBLE_CONFIG: /home/bendem/.cache/molecule/nexus/default/ansible.cfg
ANSIBLE_FILTER_PLUGINS: /home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/lib/python3.8/site-packages/molecule/provisioner/ansible/plugins/filter:/home/bendem/.cache/molecule/nexus/default/plugins/filter:/home/bendem/projects/architecture.vdl/ansible-10-486.git/ansible/playbooks/nexus/plugins/filter:/home/bendem/.ansible/plugins/filter:/usr/share/ansible/plugins/filter
ANSIBLE_LIBRARY: /home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/lib/python3.8/site-packages/molecule/provisioner/ansible/plugins/modules:/home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/lib/python3.8/site-packages/molecule_vagrant/modules:/home/bendem/.cache/molecule/nexus/default/library:/home/bendem/projects/architecture.vdl/ansible-10-486.git/ansible/playbooks/nexus/library:/home/bendem/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
ANSIBLE_ROLES_PATH: /home/bendem/.cache/molecule/nexus/default/roles:/home/bendem/projects/architecture.vdl/ansible-10-486.git/ansible/playbooks:/home/bendem/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/bendem/projects/architecture.vdl/ansible-10-486.git/ansible/roles

DEBUG: MOLECULE ENVIRONMENT
---
MOLECULE_DEBUG: 'True'
MOLECULE_DEPENDENCY_NAME: galaxy
MOLECULE_DRIVER_NAME: vagrant
MOLECULE_ENV_FILE: /home/bendem/projects/architecture.vdl/ansible-10-486.git/ansible/playbooks/nexus/.env.yml
MOLECULE_EPHEMERAL_DIRECTORY: /home/bendem/.cache/molecule/nexus/default
MOLECULE_FILE: /home/bendem/.cache/molecule/nexus/default/molecule.yml
MOLECULE_INSTANCE_CONFIG: /home/bendem/.cache/molecule/nexus/default/instance_config.yml
MOLECULE_INVENTORY_FILE: /home/bendem/.cache/molecule/nexus/default/inventory/ansible_inventory.yml
MOLECULE_PROJECT_DIRECTORY: /home/bendem/projects/architecture.vdl/ansible-10-486.git/ansible/playbooks/nexus
MOLECULE_PROVISIONER_NAME: ansible
MOLECULE_SCENARIO_DIRECTORY: /home/bendem/projects/architecture.vdl/ansible-10-486.git/ansible/playbooks/nexus/molecule/default
MOLECULE_SCENARIO_NAME: default
MOLECULE_STATE_FILE: /home/bendem/.cache/molecule/nexus/default/state.yml
MOLECULE_VERIFIER_NAME: ansible
MOLECULE_VERIFIER_TEST_DIRECTORY: /home/bendem/projects/architecture.vdl/ansible-10-486.git/ansible/playbooks/nexus/molecule/default/molecule

DEBUG: SHELL REPLAY
ANSIBLE_COLLECTIONS_PATHS=/home/bendem/.cache/molecule/nexus/default/collections:/home/bendem/.ansible:/usr/share/ansible/collections:/etc/ansible/collections ANSIBLE_CONFIG=/home/bendem/.cache/molecule/nexus/default/ansible.cfg ANSIBLE_FILTER_PLUGINS=/home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/lib/python3.8/site-packages/molecule/provisioner/ansible/plugins/filter:/home/bendem/.cache/molecule/nexus/default/plugins/filter:/home/bendem/projects/architecture.vdl/ansible-10-486.git/ansible/playbooks/nexus/plugins/filter:/home/bendem/.ansible/plugins/filter:/usr/share/ansible/plugins/filter ANSIBLE_LIBRARY=/home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/lib/python3.8/site-packages/molecule/provisioner/ansible/plugins/modules:/home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/lib/python3.8/site-packages/molecule_vagrant/modules:/home/bendem/.cache/molecule/nexus/default/library:/home/bendem/projects/architecture.vdl/ansible-10-486.git/ansible/playbooks/nexus/library:/home/bendem/.ansible/plugins/modules:/usr/share/ansible/plugins/modules ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3 ANSIBLE_ROLES_PATH=/home/bendem/.cache/molecule/nexus/default/roles:/home/bendem/projects/architecture.vdl/ansible-10-486.git/ansible/playbooks:/home/bendem/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/bendem/projects/architecture.vdl/ansible-10-486.git/ansible/roles MOLECULE_DEBUG=True MOLECULE_DEPENDENCY_NAME=galaxy MOLECULE_DRIVER_NAME=vagrant MOLECULE_ENV_FILE=/home/bendem/projects/architecture.vdl/ansible-10-486.git/ansible/playbooks/nexus/.env.yml MOLECULE_EPHEMERAL_DIRECTORY=/home/bendem/.cache/molecule/nexus/default MOLECULE_FILE=/home/bendem/.cache/molecule/nexus/default/molecule.yml MOLECULE_INSTANCE_CONFIG=/home/bendem/.cache/molecule/nexus/default/instance_config.yml MOLECULE_INVENTORY_FILE=/home/bendem/.cache/molecule/nexus/default/inventory/ansible_inventory.yml MOLECULE_PROJECT_DIRECTORY=/home/bendem/projects/architecture.vdl/ansible-10-486.git/ansible/playbooks/nexus MOLECULE_PROVISIONER_NAME=ansible MOLECULE_SCENARIO_DIRECTORY=/home/bendem/projects/architecture.vdl/ansible-10-486.git/ansible/playbooks/nexus/molecule/default MOLECULE_SCENARIO_NAME=default MOLECULE_STATE_FILE=/home/bendem/.cache/molecule/nexus/default/state.yml MOLECULE_VERIFIER_NAME=ansible MOLECULE_VERIFIER_TEST_DIRECTORY=/home/bendem/projects/architecture.vdl/ansible-10-486.git/ansible/playbooks/nexus/molecule/default/molecule

DEBUG: COMMAND
/home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/bin/ansible-playbook --skip-tags=molecule-notest,notest --diff --inventory=/home/bendem/.cache/molecule/nexus/default/inventory /home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/lib/python3.8/site-packages/molecule_vagrant/playbooks/create.yml -vvv

    ansible-playbook 2.9.9
      config file = /home/bendem/.cache/molecule/nexus/default/ansible.cfg
      configured module search path = ['/home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/lib/python3.8/site-packages/molecule/provisioner/ansible/plugins/modules', '/home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/lib/python3.8/site-packages/molecule_vagrant/modules', '/home/bendem/.cache/molecule/nexus/default/library', '/home/bendem/projects/architecture.vdl/ansible-10-486.git/ansible/playbooks/nexus/library', '/home/bendem/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
      ansible python module location = /home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/lib/python3.8/site-packages/ansible
      executable location = /home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/bin/ansible-playbook
      python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]
    Using /home/bendem/.cache/molecule/nexus/default/ansible.cfg as config file
    host_list declined parsing /home/bendem/.cache/molecule/nexus/default/inventory/ansible_inventory.yml as it did not pass its verify_file() method
    script declined parsing /home/bendem/.cache/molecule/nexus/default/inventory/ansible_inventory.yml as it did not pass its verify_file() method
    Parsed /home/bendem/.cache/molecule/nexus/default/inventory/ansible_inventory.yml inventory source with yaml plugin

    PLAYBOOK: create.yml ***********************************************************
    1 plays in /home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/lib/python3.8/site-packages/molecule_vagrant/playbooks/create.yml

    PLAY [Create] ******************************************************************
    META: ran handlers

    TASK [Create molecule instance(s)] *********************************************
    task path: /home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/lib/python3.8/site-packages/molecule_vagrant/playbooks/create.yml:8
    <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: bendem
    <127.0.0.1> EXEC /bin/sh -c 'echo ~bendem && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/bendem/.ansible/tmp `"&& mkdir /home/bendem/.ansible/tmp/ansible-tmp-1593682802.9629104-22617-106269756065218 && echo ansible-tmp-1593682802.9629104-22617-106269756065218="` echo /home/bendem/.ansible/tmp/ansible-tmp-1593682802.9629104-22617-106269756065218 `" ) && sleep 0'
    Using module file /home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/lib/python3.8/site-packages/molecule_vagrant/modules/vagrant.py
    <127.0.0.1> PUT /home/bendem/.ansible/tmp/ansible-local-22610_l5ambu1/tmp7c7wv91b TO /home/bendem/.ansible/tmp/ansible-tmp-1593682802.9629104-22617-106269756065218/AnsiballZ_vagrant.py
    <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/bendem/.ansible/tmp/ansible-tmp-1593682802.9629104-22617-106269756065218/ /home/bendem/.ansible/tmp/ansible-tmp-1593682802.9629104-22617-106269756065218/AnsiballZ_vagrant.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '/home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/bin/python /home/bendem/.ansible/tmp/ansible-tmp-1593682802.9629104-22617-106269756065218/AnsiballZ_vagrant.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/bendem/.ansible/tmp/ansible-tmp-1593682802.9629104-22617-106269756065218/ > /dev/null 2>&1 && sleep 0'
    changed: [localhost] => (item=instance01.local) => {
        "Host": "instance01.local",
        "HostName": "127.0.0.1",
        "IdentitiesOnly": "yes",
        "IdentityFile": "/home/bendem/.cache/molecule/nexus/default/.vagrant/machines/instance01.local/virtualbox/private_key",
        "LogLevel": "FATAL",
        "PasswordAuthentication": "no",
        "Port": "2222",
        "StrictHostKeyChecking": "no",
        "User": "vagrant",
        "UserKnownHostsFile": "/dev/null",
        "ansible_loop_var": "item",
        "changed": true,
        "invocation": {
            "module_args": {
                "config_options": {},
                "force_stop": false,
                "instance_interfaces": [],
                "instance_name": "instance01.local",
                "instance_raw_config_args": [
                    "vm.network \"forwarded_port\", guest: 443, host: 4443",
                    "vm.network \"forwarded_port\", guest: 4444, host: 4444"
                ],
                "platform_box": "centos/8",
                "platform_box_url": null,
                "platform_box_version": null,
                "provider_cpus": 1,
                "provider_memory": 128,
                "provider_name": "VBox",
                "provider_options": {},
                "provider_override_args": null,
                "provider_raw_config_args": [
                    ""
                ],
                "provision": false,
                "state": "up"
            }
        },
        "item": {
            "box": "centos/8",
            "cpus": 1,
            "groups": [
                "docker_hosts",
                "nexus",
                "local"
            ],
            "instance_raw_config_args": [
                "vm.network \"forwarded_port\", guest: 443, host: 4443",
                "vm.network \"forwarded_port\", guest: 4444, host: 4444"
            ],
            "memory": 128,
            "name": "instance01.local",
            "provider_raw_config_args": null
        },
        "log": "/home/bendem/.cache/molecule/nexus/default/vagrant-instance01.local.out"
    }
    <127.0.0.1> EXEC /bin/sh -c 'echo ~bendem && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/bendem/.ansible/tmp `"&& mkdir /home/bendem/.ansible/tmp/ansible-tmp-1593682856.9482248-22617-180282126220523 && echo ansible-tmp-1593682856.9482248-22617-180282126220523="` echo /home/bendem/.ansible/tmp/ansible-tmp-1593682856.9482248-22617-180282126220523 `" ) && sleep 0'
    Using module file /home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/lib/python3.8/site-packages/molecule_vagrant/modules/vagrant.py
    <127.0.0.1> PUT /home/bendem/.ansible/tmp/ansible-local-22610_l5ambu1/tmp14r3guaw TO /home/bendem/.ansible/tmp/ansible-tmp-1593682856.9482248-22617-180282126220523/AnsiballZ_vagrant.py
    <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/bendem/.ansible/tmp/ansible-tmp-1593682856.9482248-22617-180282126220523/ /home/bendem/.ansible/tmp/ansible-tmp-1593682856.9482248-22617-180282126220523/AnsiballZ_vagrant.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '/home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/bin/python /home/bendem/.ansible/tmp/ansible-tmp-1593682856.9482248-22617-180282126220523/AnsiballZ_vagrant.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/bendem/.ansible/tmp/ansible-tmp-1593682856.9482248-22617-180282126220523/ > /dev/null 2>&1 && sleep 0'
    failed: [localhost] (item=instance02.local) => {
        "ansible_loop_var": "item",
        "changed": false,
        "cmd": [
            "/bin/vagrant",
            "up",
            "--no-provision"
        ],
        "invocation": {
            "module_args": {
                "config_options": {},
                "force_stop": false,
                "instance_interfaces": [],
                "instance_name": "instance02.local",
                "instance_raw_config_args": [
                    "vm.network \"forwarded_port\", guest: 443, host: 4453",
                    "vm.network \"forwarded_port\", guest: 4444, host: 4454"
                ],
                "platform_box": "centos/7",
                "platform_box_url": null,
                "platform_box_version": null,
                "provider_cpus": 1,
                "provider_memory": 128,
                "provider_name": "VBox",
                "provider_options": {},
                "provider_override_args": null,
                "provider_raw_config_args": [
                    ""
                ],
                "provision": false,
                "state": "up"
            }
        },
        "item": {
            "box": "centos/7",
            "cpus": 1,
            "groups": [
                "docker_hosts",
                "nexus",
                "local"
            ],
            "instance_raw_config_args": [
                "vm.network \"forwarded_port\", guest: 443, host: 4453",
                "vm.network \"forwarded_port\", guest: 4444, host: 4454"
            ],
            "memory": 128,
            "name": "instance02.local",
            "provider_raw_config_args": null
        },
        "msg": "ERROR: See log file '/home/bendem/.cache/molecule/nexus/default/vagrant-instance02.local.err'",
        "rc": 1,
        "stderr": "### 2020-07-02 11:24:42 ###\n### 2020-07-02 11:24:42 ###\nThe guest machine entered an invalid state while waiting for it\nto boot. Valid states are 'starting, running'. The machine is in the\n'paused' state. Please verify everything is configured\nproperly and try again.\n\nIf the provider you're using has a GUI that comes with it,\nit is often helpful to open that and watch the machine, since the\nGUI often has more helpful error messages than Vagrant can retrieve.\nFor example, if you're using VirtualBox, run `vagrant up` while the\nVirtualBox GUI is open.\n\nThe primary issue for this error is that the provider you're using\nis not properly configured. This is very rarely a Vagrant issue.\n### 2020-07-02 11:29:55 ###\n### 2020-07-02 11:29:55 ###\nThe guest machine entered an invalid state while waiting for it\nto boot. Valid states are 'starting, running'. The machine is in the\n'paused' state. Please verify everything is configured\nproperly and try again.\n\nIf the provider you're using has a GUI that comes with it,\nit is often helpful to open that and watch the machine, since the\nGUI often has more helpful error messages than Vagrant can retrieve.\nFor example, if you're using VirtualBox, run `vagrant up` while the\nVirtualBox GUI is open.\n\nThe primary issue for this error is that the provider you're using\nis not properly configured. This is very rarely a Vagrant issue.\n### 2020-07-02 11:33:35 ###\n### 2020-07-02 11:33:35 ###\n### 2020-07-02 11:33:35 ###\n### 2020-07-02 11:34:53 ###\n### 2020-07-02 11:39:34 ###\n### 2020-07-02 11:39:34 ###\n### 2020-07-02 11:39:34 ###\n### 2020-07-02 11:40:57 ###\n### 2020-07-02 11:40:57 ###\nThe guest machine entered an invalid state while waiting for it\nto boot. Valid states are 'starting, running'. The machine is in the\n'paused' state. Please verify everything is configured\nproperly and try again.\n\nIf the provider you're using has a GUI that comes with it,\nit is often helpful to open that and watch the machine, since the\nGUI often has more helpful error messages than Vagrant can retrieve.\nFor example, if you're using VirtualBox, run `vagrant up` while the\nVirtualBox GUI is open.\n\nThe primary issue for this error is that the provider you're using\nis not properly configured. This is very rarely a Vagrant issue.\n",
        "stderr_lines": [
            "### 2020-07-02 11:24:42 ###",
            "### 2020-07-02 11:24:42 ###",
            "The guest machine entered an invalid state while waiting for it",
            "to boot. Valid states are 'starting, running'. The machine is in the",
            "'paused' state. Please verify everything is configured",
            "properly and try again.",
            "",
            "If the provider you're using has a GUI that comes with it,",
            "it is often helpful to open that and watch the machine, since the",
            "GUI often has more helpful error messages than Vagrant can retrieve.",
            "For example, if you're using VirtualBox, run `vagrant up` while the",
            "VirtualBox GUI is open.",
            "",
            "The primary issue for this error is that the provider you're using",
            "is not properly configured. This is very rarely a Vagrant issue.",
            "### 2020-07-02 11:29:55 ###",
            "### 2020-07-02 11:29:55 ###",
            "The guest machine entered an invalid state while waiting for it",
            "to boot. Valid states are 'starting, running'. The machine is in the",
            "'paused' state. Please verify everything is configured",
            "properly and try again.",
            "",
            "If the provider you're using has a GUI that comes with it,",
            "it is often helpful to open that and watch the machine, since the",
            "GUI often has more helpful error messages than Vagrant can retrieve.",
            "For example, if you're using VirtualBox, run `vagrant up` while the",
            "VirtualBox GUI is open.",
            "",
            "The primary issue for this error is that the provider you're using",
            "is not properly configured. This is very rarely a Vagrant issue.",
            "### 2020-07-02 11:33:35 ###",
            "### 2020-07-02 11:33:35 ###",
            "### 2020-07-02 11:33:35 ###",
            "### 2020-07-02 11:34:53 ###",
            "### 2020-07-02 11:39:34 ###",
            "### 2020-07-02 11:39:34 ###",
            "### 2020-07-02 11:39:34 ###",
            "### 2020-07-02 11:40:57 ###",
            "### 2020-07-02 11:40:57 ###",
            "The guest machine entered an invalid state while waiting for it",
            "to boot. Valid states are 'starting, running'. The machine is in the",
            "'paused' state. Please verify everything is configured",
            "properly and try again.",
            "",
            "If the provider you're using has a GUI that comes with it,",
            "it is often helpful to open that and watch the machine, since the",
            "GUI often has more helpful error messages than Vagrant can retrieve.",
            "For example, if you're using VirtualBox, run `vagrant up` while the",
            "VirtualBox GUI is open.",
            "",
            "The primary issue for this error is that the provider you're using",
            "is not properly configured. This is very rarely a Vagrant issue."
        ]
    }

    PLAY RECAP *********************************************************************
    localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

ERROR:
```
</details>

One of the instance didn't fail but is not marked as created:

<details>
<summary>click for logs</summary>

```
(ansible) ➜  nexus git:(main) ✗ molecule -c molecule/default/wsl.yml --debug list
--> Inventory /home/bendem/projects/architecture.vdl/ansible-10-486.git/ansible/playbooks/nexus/molecule/default/../../../../inventory/group_vars/ linked to /home/bendem/.cache/molecule/nexus/default/inventory/group_vars
Instance Name     Driver Name    Provisioner Name    Scenario Name    Created    Converged
----------------  -------------  ------------------  ---------------  ---------  -----------
instance01.local  vagrant        ansible             default          false      false
instance02.local  vagrant        ansible             default          false      false
```
</details>

Second run, I get an error on the instance that got created on first run:

<details>
<summary>click for logs</summary>

```
    TASK [Create molecule instance(s)] *********************************************
    task path: /home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/lib/python3.8/site-packages/molecule_vagrant/playbooks/create.yml:8
    <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: bendem
    <127.0.0.1> EXEC /bin/sh -c 'echo ~bendem && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/bendem/.ansible/tmp `"&& mkdir /home/bendem/.ansible/tmp/ansible-tmp-1593682989.8318512-19364-76339248982754 && echo ansible-tmp-1593682989.8318512-19364-76339248982754="` echo /home/bendem/.ansible/tmp/ansible-tmp-1593682989.8318512-19364-76339248982754 `" ) && sleep 0'
    Using module file /home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/lib/python3.8/site-packages/molecule_vagrant/modules/vagrant.py
    <127.0.0.1> PUT /home/bendem/.ansible/tmp/ansible-local-1935766ol2v8g/tmpi5dt4hop TO /home/bendem/.ansible/tmp/ansible-tmp-1593682989.8318512-19364-76339248982754/AnsiballZ_vagrant.py
    <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/bendem/.ansible/tmp/ansible-tmp-1593682989.8318512-19364-76339248982754/ /home/bendem/.ansible/tmp/ansible-tmp-1593682989.8318512-19364-76339248982754/AnsiballZ_vagrant.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '/home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/bin/python /home/bendem/.ansible/tmp/ansible-tmp-1593682989.8318512-19364-76339248982754/AnsiballZ_vagrant.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/bendem/.ansible/tmp/ansible-tmp-1593682989.8318512-19364-76339248982754/ > /dev/null 2>&1 && sleep 0'
    The full traceback is:
    Traceback (most recent call last):
      File "/home/bendem/.ansible/tmp/ansible-tmp-1593682989.8318512-19364-76339248982754/AnsiballZ_vagrant.py", line 102, in <module>
        _ansiballz_main()
      File "/home/bendem/.ansible/tmp/ansible-tmp-1593682989.8318512-19364-76339248982754/AnsiballZ_vagrant.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/bendem/.ansible/tmp/ansible-tmp-1593682989.8318512-19364-76339248982754/AnsiballZ_vagrant.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible.modules.vagrant', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib/python3.8/runpy.py", line 206, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.8/runpy.py", line 96, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_vagrant_payload_blms40vr/ansible_vagrant_payload.zip/ansible/modules/vagrant.py", line 632, in <module>
      File "/tmp/ansible_vagrant_payload_blms40vr/ansible_vagrant_payload.zip/ansible/modules/vagrant.py", line 628, in main
    AttributeError: 'AnsibleModule' object has no attribute 'result'
    failed: [localhost] (item=instance01.local) => {
        "ansible_loop_var": "item",
        "changed": false,
        "item": {
            "box": "centos/8",
            "cpus": 1,
            "groups": [
                "docker_hosts",
                "nexus",
                "local"
            ],
            "instance_raw_config_args": [
                "vm.network \"forwarded_port\", guest: 443, host: 4443",
                "vm.network \"forwarded_port\", guest: 4444, host: 4444"
            ],
            "memory": 128,
            "name": "instance01.local",
            "provider_raw_config_args": null
        },
        "module_stderr": "Traceback (most recent call last):\n  File \"/home/bendem/.ansible/tmp/ansible-tmp-1593682989.8318512-19364-76339248982754/AnsiballZ_vagrant.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/bendem/.ansible/tmp/ansible-tmp-1593682989.8318512-19364-76339248982754/AnsiballZ_vagrant.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/bendem/.ansible/tmp/ansible-tmp-1593682989.8318512-19364-76339248982754/AnsiballZ_vagrant.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.vagrant', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 206, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_vagrant_payload_blms40vr/ansible_vagrant_payload.zip/ansible/modules/vagrant.py\", line 632, in <module>\n  File \"/tmp/ansible_vagrant_payload_blms40vr/ansible_vagrant_payload.zip/ansible/modules/vagrant.py\", line 628, in main\nAttributeError: 'AnsibleModule' object has no attribute 'result'\n",
        "module_stdout": "",
        "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
        "rc": 1
    }
```
</details>

Details:
I'm running ansible in WSL1 Ubuntu 20.04 with VBox on the windows host using VBox (Version 6.1.10 r138449 (Qt5.6.2)) with hyperv integration:

```
(ansible) ➜  nexus git:(main) ✗ uname -a
Linux CL1277 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
(ansible) ➜  nexus git:(main) ✗ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
(ansible) ➜  nexus git:(main) ✗ ansible --version
ansible 2.9.9
  config file = None
  configured module search path = ['/home/bendem/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/lib/python3.8/site-packages/ansible
  executable location = /home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/bin/ansible
  python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]
(ansible) ➜  nexus git:(main) ✗ vagrant --version
Vagrant 2.2.9
(ansible) ➜  nexus git:(main) ✗ molecule --version
molecule 3.0.4
   ansible==2.9.9 python==3.8

>ver

Microsoft Windows [version 10.0.18363.900]
```

**Comment by apatard** [comment]
Current multiplatform support is more or less working by luck. It's overwriting the vagrant configuration when switching from one instance to an other. That's why you're seeing such behaviour.

This pull request may solve your issue : https://github.com/ansible-community/molecule-vagrant/pull/31. I hope to be able to review this PR soon as proper multiplatform support is needed/wanted.

**Comment by apatard** [comment]
Finally, a new release with proper multiplatform support has been done and I was waiting for it before closing this bug.
@bendem Do you mind if I close it ?

**Comment by bendem** [comment]
If the problem is fixed, feel free to close the issue, I have not used molecule vagrant recently so I can't tell by myself
